### ISSUE TITLE
Transparent Window during sign in and avoid animation

### ISSUE THREAD

**Issue by pritishgeorge** [AppWerft/Ti.GoogleSignIn#30] opened 2019-02-16 10:36 UTC
Currently when i click on google sign in a black window is opened. It would be great if there was a option to make the background transparent and avoid animation so that the activity indicator in the background is visible and the entire process is seamless

**Comment by hansemannn** [comment] 2019-03-22 22:19
Duplicate of #9 incl. fix.

**Closed** 2019-03-25 14:39 UTC
